/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurfRouteImport } from './routes/turf'
import { Route as VotersRouteImport } from './routes/voters'
import { Route as WalkRouteImport } from './routes/walk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurfRoute = TurfRouteImport.update({
  id: '/turf',
  path: '/turf',
  getParentRoute: () => rootRouteImport,
} as any)
const VotersRoute = VotersRouteImport.update({
  id: '/voters',
  path: '/voters',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/turf': typeof TurfRoute
  '/voters': typeof VotersRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/turf': typeof TurfRoute
  '/voters': typeof VotersRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/turf': typeof TurfRoute
  '/voters': typeof VotersRoute
  '/walk': typeof WalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/turf' | '/voters' | '/walk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/turf' | '/voters' | '/walk'
  id: '__root__' | '/' | '/turf' | '/voters' | '/walk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TurfRoute: typeof TurfRoute
  VotersRoute: typeof VotersRoute
  WalkRoute: typeof WalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turf': {
      id: '/turf'
      path: '/turf'
      fullPath: '/turf'
      preLoaderRoute: typeof TurfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voters': {
      id: '/voters'
      path: '/voters'
      fullPath: '/voters'
      preLoaderRoute: typeof VotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TurfRoute: TurfRoute,
  VotersRoute: VotersRoute,
  WalkRoute: WalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
